/* Cache-first over a versioned precache. PRECACHE is generated by
   tools/build.mjs — do not hand-edit the list. Offline is the normal case for
   this product, not a degraded one. */

const VERSION = "daf27ceafc45";
const CACHE = `fp-${VERSION}`;

/* __PRECACHE_START__ */
const PRECACHE = [
  "./",
  "assets/fonts/baloo-2-latin-600-normal.woff2",
  "assets/fonts/nunito-latin-400-normal.woff2",
  "assets/fonts/nunito-latin-700-normal.woff2",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/icon-maskable.png",
  "assets/mark.svg",
  "content/animals/01-every-body-is-a-compromise.json",
  "content/animals/02-big-small-and-why-it-matters.json",
  "content/animals/03-how-to-move-without-wheels.json",
  "content/animals/04-behaviour-is-inherited-too.json",
  "content/authored.json",
  "content/biomolecules/01-four-families-all-of-life.json",
  "content/biomolecules/02-sugar-is-a-battery.json",
  "content/biomolecules/03-why-oil-and-water-wont-mix.json",
  "content/biomolecules/04-beads-that-fold-into-machines.json",
  "content/biotechnology/01-making-cells-work-for-you.json",
  "content/biotechnology/02-copying-dna-on-purpose.json",
  "content/biotechnology/03-reading-a-genome.json",
  "content/biotechnology/04-insulin-from-bacteria.json",
  "content/cells/01-city-in-a-speck.json",
  "content/cells/02-the-wall-that-chooses.json",
  "content/cells/03-the-power-plant.json",
  "content/cells/04-the-instruction-room.json",
  "content/cells/05-build-a-cell.json",
  "content/crispr/01-scissors-that-read-first.json",
  "content/crispr/02-where-the-scissors-came-from.json",
  "content/crispr/03-cutting-the-right-place.json",
  "content/crispr/04-what-could-go-wrong.json",
  "content/crispr/05-edit-a-gene.json",
  "content/curriculum.json",
  "content/describing-motion/01-here-to-there.json",
  "content/describing-motion/02-how-fast-is-fast.json",
  "content/describing-motion/03-speeding-up-and-slowing-down.json",
  "content/describing-motion/04-who-is-moving.json",
  "content/development/01-one-cell-becomes-an-animal.json",
  "content/development/02-where-is-the-instruction-for-leg.json",
  "content/development/03-the-same-toolkit-in-a-fly-and-in-you.json",
  "content/development/04-build-a-body-plan.json",
  "content/disease/01-what-makes-you-ill.json",
  "content/disease/02-how-something-spreads.json",
  "content/disease/03-the-outbreak-detective.json",
  "content/disease/04-why-some-diseases-vanish.json",
  "content/dna/01-two-metres-in-a-speck.json",
  "content/dna/02-the-four-letters.json",
  "content/dna/03-the-ladder-that-copies-itself.json",
  "content/dna/04-mistakes-get-made.json",
  "content/dna/05-reading-without-tangling.json",
  "content/ecology/01-nothing-eats-alone.json",
  "content/ecology/02-energy-runs-out-going-up.json",
  "content/ecology/03-the-number-that-stops-growing.json",
  "content/ecology/04-remove-one-thing.json",
  "content/ecology/05-build-a-food-web.json",
  "content/environmental-science/01-the-carbon-round-trip.json",
  "content/environmental-science/02-why-a-degree-matters.json",
  "content/environmental-science/03-extinction-is-forever.json",
  "content/environmental-science/04-fix-one-thing.json",
  "content/evolution/01-what-would-change-your-mind.json",
  "content/evolution/02-the-same-bones-in-different-jobs.json",
  "content/evolution/03-the-order-in-the-rocks.json",
  "content/evolution/04-family-trees-written-in-dna.json",
  "content/evolution/05-how-much-can-change.json",
  "content/future-biology/01-growing-an-organ.json",
  "content/future-biology/02-bringing-back-the-dead.json",
  "content/future-biology/03-should-we.json",
  "content/future-biology/04-what-you-would-build.json",
  "content/genes/01-what-is-a-gene-for.json",
  "content/genes/02-same-book-different-pages.json",
  "content/genes/03-two-copies-of-everything.json",
  "content/genes/04-your-grandmothers-eyes.json",
  "content/hints.json",
  "content/human-body/01-a-colony-of-thirty-trillion.json",
  "content/human-body/02-the-pump-that-never-stops.json",
  "content/human-body/03-breathing-is-not-for-air.json",
  "content/human-body/04-the-longest-tube.json",
  "content/human-body/05-everything-talks-to-everything.json",
  "content/immunity/01-the-army-with-no-general.json",
  "content/immunity/02-recognise-remember-respond.json",
  "content/immunity/03-how-a-vaccine-teaches.json",
  "content/immunity/04-when-the-army-attacks-you.json",
  "content/immunity/05-build-a-defence.json",
  "content/kinetic-potential/01-the-energy-of-moving.json",
  "content/kinetic-potential/02-the-energy-of-where.json",
  "content/kinetic-potential/03-trading-one-for-the-other.json",
  "content/kinetic-potential/04-build-a-roller-coaster.json",
  "content/medicine/01-finding-the-right-molecule.json",
  "content/medicine/02-why-trials-have-two-groups.json",
  "content/medicine/03-resistance.json",
  "content/medicine/04-design-a-treatment.json",
  "content/microbiology/01-the-invisible-majority.json",
  "content/microbiology/02-fast-life.json",
  "content/microbiology/03-the-ones-that-live-in-you.json",
  "content/microbiology/04-growing-something-you-cannot-see.json",
  "content/natural-selection/01-the-beetles-that-vanished.json",
  "content/natural-selection/02-fitness-is-not-strength.json",
  "content/natural-selection/03-the-peppered-moth.json",
  "content/natural-selection/04-why-antibiotics-stop-working.json",
  "content/neuroscience/01-thinking-is-electricity.json",
  "content/neuroscience/02-the-gap-that-matters.json",
  "content/neuroscience/03-your-brain-edits-what-you-see.json",
  "content/neuroscience/04-memory-is-rebuilt-not-replayed.json",
  "content/neuroscience/05-wire-a-reflex.json",
  "content/newtons-laws/01-the-first-rule.json",
  "content/newtons-laws/02-the-second-rule.json",
  "content/newtons-laws/03-the-third-rule.json",
  "content/newtons-laws/04-when-forces-balance.json",
  "content/newtons-laws/05-build-a-force-diagram.json",
  "content/nutrition/01-food-is-two-things.json",
  "content/nutrition/02-what-happens-to-a-sandwich.json",
  "content/nutrition/03-the-vitamin-nobody-could-find.json",
  "content/nutrition/04-why-diets-disagree.json",
  "content/oscillation/01-the-pull-back.json",
  "content/plants/01-eating-light.json",
  "content/plants/02-the-plumbing-that-has-no-pump.json",
  "content/plants/03-why-leaves-are-flat.json",
  "content/plants/04-flowers-are-advertisements.json",
  "content/plants/05-build-a-plant.json",
  "content/proteins/01-a-string-that-folds-itself.json",
  "content/proteins/02-shape-is-the-job.json",
  "content/proteins/03-the-enzyme-and-the-lock.json",
  "content/proteins/04-when-folding-goes-wrong.json",
  "content/proteins/05-build-a-protein.json",
  "content/reviews.json",
  "content/space-biology/01-life-without-weight.json",
  "content/space-biology/02-could-anything-live-on-mars.json",
  "content/space-biology/03-the-toughest-animal-alive.json",
  "content/space-biology/04-pack-a-spaceship-garden.json",
  "content/specimen-art.json",
  "content/synthetic-biology/01-biology-as-parts.json",
  "content/synthetic-biology/02-a-circuit-made-of-genes.json",
  "content/synthetic-biology/03-the-smallest-possible-life.json",
  "content/synthetic-biology/04-design-an-organism.json",
  "content/what-is-life/01-the-line-you-cannot-draw.json",
  "content/what-is-life/02-seven-rules-and-their-exceptions.json",
  "content/what-is-life/03-the-fire-that-isnt-alive.json",
  "content/what-is-life/04-could-life-start-by-itself.json",
  "css/app.css",
  "index.html",
  "js/app.js",
  "js/audio.js",
  "js/author/index.js",
  "js/author/stages.js",
  "js/author/validate.js",
  "js/components/board.js",
  "js/components/predict.js",
  "js/components/quiz.js",
  "js/components/slider.js",
  "js/curriculum.js",
  "js/el.js",
  "js/icons.js",
  "js/lesson/celebrate.js",
  "js/lesson/parts.js",
  "js/lesson/parts/build.js",
  "js/lesson/parts/sim.js",
  "js/lesson/parts/slider.js",
  "js/lesson/parts/weigh.js",
  "js/lesson/review.js",
  "js/lesson/runner.js",
  "js/lesson/tutor.js",
  "js/lesson/view.js",
  "js/level.js",
  "js/reward.js",
  "js/scheduler.js",
  "js/screens.js",
  "js/sims/base.js",
  "js/sims/coaster.js",
  "js/sims/energy.js",
  "js/sims/folding.js",
  "js/sims/forces.js",
  "js/sims/hand.js",
  "js/sims/incline.js",
  "js/sims/membrane.js",
  "js/sims/outbreak.js",
  "js/sims/pendulum.js",
  "js/sims/replication.js",
  "js/sims/selection.js",
  "js/sims/spike.js",
  "js/sims/stomata.js",
  "js/sims/web.js",
  "js/state.js",
  "manifest.webmanifest"
];
/* __PRECACHE_END__ */

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const { request } = e;
  if (request.method !== "GET" || new URL(request.url).origin !== location.origin) return;

  // Hash routing means every in-app route IS the shell document, so a cold
  // offline start needs the shell as a fallback. But falling back to the shell
  // for *every* navigation silently shadows any other real page at this origin
  // — styleguide.html was served index.html and looked like a broken build.
  // Try the exact document first; use the shell only when there isn't one.
  if (request.mode === "navigate") {
    e.respondWith(
      caches.match(request)
        .then((hit) => hit || fetch(request))
        .catch(() => caches.match("./"))
    );
    return;
  }

  e.respondWith(
    caches.match(request).then((hit) =>
      hit || fetch(request).then((res) => {
        // Only same-origin OK responses are worth keeping; opaque ones lie
        // about their status and poison the cache.
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(request, copy));
        }
        return res;
      }).catch(() => hit)
    )
  );
});
