"""Writes css/worlds.css. Every value is solved against a WCAG gate, never chosen by eye.
Run after changing a hue:  python3 tools/gen-palette.py"""
import importlib.util, sys, pathlib
spec = importlib.util.spec_from_file_location("p", pathlib.Path(__file__).with_name("palette.py"))
p = importlib.util.module_from_spec(spec); spec.loader.exec_module(p)
hexof, in_gamut, solve, contrast = p.hexof, p.in_gamut, p.solve, p.contrast

WORLDS = [("origins",190),("code",295),("change",55),("bodies",340),("living",122),("frontier",250)]
SEM    = [("correct",152),("wrong",22),("discovery",90)]
PAPER, NIGHT = "#FDFBF7", "#191614"
INK_L, INK_D = "#241F1B", "#F7F3ED"
TEXT_GATE, LINE_GATE = 4.60, 3.10

def gam(L, C, h):
    while C > 0.005 and not in_gamut(L, C, h): C -= 0.005
    return hexof(L, C, h)

def ramp(h, ground, ink, dark, extra_grounds=()):
    """`ground` is the page; `extra_grounds` are the other surfaces this ramp's
    text and strokes can land on (cards, sunken panels, its own tint). Text is
    solved against all of them at once."""
    d = not dark
    fill_L, step = (0.87, 0.01) if not dark else (0.34, -0.01)
    while True:
        fill = gam(fill_L, 0.105, h)
        if contrast(fill, ink) >= TEXT_GATE: break
        fill_L += step
    tint = gam(0.965 if not dark else 0.225, 0.035, h)
    grounds = [ground, tint, *extra_grounds]
    return {"tint": tint, "fill": fill,
            "line": solve(h, 0.16, grounds, LINE_GATE, darker=d)[2],
            "text": solve(h, 0.16, grounds, TEXT_GATE, darker=d)[2],
            "deep": gam(0.30 if not dark else 0.90, 0.09, h)}

def surfaces(ground, dark):
    """Every neutral background a text colour can composite onto."""
    return [ground,
            gam(0.995 if not dark else 0.215, 0.004, 60),   # --surface
            gam(0.955 if not dark else 0.185, 0.008, 60)]   # --sunk

def scope(ground, ink, dark):
    out, fails = [], []
    surf = surfaces(ground, dark)
    for key, h in WORLDS + SEM:
        r = ramp(h, ground, ink, dark, extra_grounds=surf[1:])
        for k, v in r.items(): out.append(f"  --w-{key}-{k}: {v};")
        checks = [*surf, r["tint"]]
        if (min(contrast(r["line"], g) for g in checks) < 3.0
                or min(contrast(r["text"], g) for g in checks) < 4.5
                or contrast(r["fill"], ink) < 4.5
                # `deep` is used as a solid fill with page-coloured text on it
                or contrast(r["deep"], ground) < 4.5):
            fails.append(key)
    return out, fails

L, fL = scope(PAPER, INK_L, False)
D, fD = scope(NIGHT, INK_D, True)
if fL or fD:
    print(f"CONTRAST GATE FAILED: {fL + fD}", file=sys.stderr); sys.exit(1)

def chrome(ground, ink, dark):
    """Neutral ink must survive every surface AND every world tint — a caption
    on a tinted card is still a caption."""
    d = not dark
    g = surfaces(ground, dark) + [ramp(h, ground, ink, dark)["tint"] for _, h in WORLDS + SEM]
    return [f"  --paper: {ground};", f"  --ink: {ink};",
            f"  --ink-2: {solve(60, 0.012, g, 7.0, darker=d)[2]};",
            f"  --ink-3: {solve(60, 0.012, g, TEXT_GATE, darker=d)[2]};",
            f"  --line: {solve(60, 0.012, g, LINE_GATE, darker=d)[2]};",
            f"  --hairline: {gam(0.925 if not dark else 0.26, 0.010, 60)};",
            f"  --surface: {gam(0.995 if not dark else 0.215, 0.004, 60)};",
            f"  --sunk: {gam(0.955 if not dark else 0.185, 0.008, 60)};",
            # Elevation ingredients. A shadow must always be DARKER than the
            # surface it falls on and a rim light always LIGHTER, so neither can
            # be derived from --ink: --ink inverts between themes and would paint
            # a white halo under every dark-mode card.
            "  --shade: 26 22 19;" if not dark else "  --shade: 0 0 0;",
            "  --rim: 255 255 255;",
            *(["  --shade-o1: .13;", "  --shade-o2: .26;", "  --rim-o: .55;"] if not dark
              else ["  --shade-o1: .55;", "  --shade-o2: .72;", "  --rim-o: .10;"])]

hdr = ("/* GENERATED by tools/gen-palette.py — do not hand-edit.\n"
       "   Every colour below was solved against a WCAG gate with margin (text 4.6:1,\n"
       "   UI stroke 3.1:1, ink-on-fill 4.6:1) rather than picked by eye. Regenerate\n"
       "   after changing a hue; the generator exits non-zero if any gate fails. */\n")
body = (hdr + ":root {\n" + "\n".join(chrome(PAPER, INK_L, False) + L) + "\n}\n\n"
        "@media (prefers-color-scheme: dark) {\n  :root {\n"
        + "\n".join("  " + s for s in chrome(NIGHT, INK_D, True) + D) + "\n  }\n}\n\n"
        '[data-theme="light"] {\n' + "\n".join(chrome(PAPER, INK_L, False) + L) + "\n}\n\n"
        '[data-theme="dark"] {\n' + "\n".join(chrome(NIGHT, INK_D, True) + D) + "\n}\n")
# Alias blocks: any subtree tagged [data-world="x"] resolves the generic
# --w-tint/fill/line/text/deep to that world's ramp, so components.css never
# names a world. Generated here so it cannot drift from the hue list.
alias = "\n/* scope aliases — components use --w-* and never name a world */\n" + "\n".join(
    '[data-world="%s"] {\n%s\n}' % (k, "\n".join(f"  --w-{r}: var(--w-{k}-{r});" for r in
        ("tint","fill","line","text","deep")))
    for k, _ in WORLDS + SEM) + "\n"
pathlib.Path("css/worlds.css").write_text(body + alias)
print(f"css/worlds.css written — {len(WORLDS)} worlds + {len(SEM)} semantics x 2 themes, all gates passed")
